### ISSUE TITLE
Update example for grpc-tools v1.9

### ISSUE THREAD

**Issue by dzemon-chwy** [badsyntax/grpc-js-types#2]
Per https://github.com/grpc/grpc-node/issues/1417, the it looks like the `sed` commands should no longer be needed in the gen script... but I can't seem to figure out what argument is supposed to go where to make this work. Can you update this repo to provide such an example?

And by the way, THANK YOU for putting this together.

**Comment by badsyntax** [comment]
Hey, i've updated the examples. See: https://github.com/badsyntax/grpc-js-types/commit/4d1dcffe2c736b752bc1eb32d9e8a544f141d74f#diff-96cc9eba287050452ce302a0fe8ccad7

BTW sed is still required to update the package paths within the generated typescript files because [this PR](https://github.com/improbable-eng/ts-protoc-gen/pull/236) is still waiting to be merged.

**Comment by dzemon-chwy** [comment]
Many thnaks!
